import { Reserve, Event, Partner, Testimonial, ImpactStats } from "@/types";

export const IMPACT_STATS: ImpactStats = {
  sqFtRestored: 35000,
  nativePlants: 3500,
  volunteers: 1500,
  volunteerHours: 4000,
  activeLocations: 21,
  citiesServed: 3,
};

export const RESERVES: Reserve[] = [
  {
    id: "1",
    slug: "la-mariposa-reserve",
    name: "La Mariposa Reserve",
    summary: "A vibrant parkway habitat bursting with California natives, supporting dozens of pollinator species in the heart of Oxnard.",
    fullStory: "What was once a strip of dead grass and concrete has been transformed into a thriving 400 sq ft pollinator corridor. Installed by 32 volunteers in a single Saturday, La Mariposa now hosts 14 native species including California Fuchsia, Hummingbird Sage, and Coyote Mint. Hummingbirds were spotted within the first week.",
    locationName: "W 5th Street Parkway",
    address: "500 W 5th Street",
    city: "Oxnard",
    region: "Ventura County",
    lat: 34.1975,
    lng: -119.177,
    installDate: "2023-03-15",
    reserveType: "kit",
    adoptionStatus: "available",
    sizeSqft: 400,
    nativePlantCount: 14,
    maintenanceStatus: "thriving",
    featured: true,
    heroPhoto: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800",
    photos: [
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800",
      "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=800",
    ],
    species: ["California Fuchsia", "Hummingbird Sage", "Coyote Mint", "Black-eyed Susan", "Toyon"],
    volunteersCount: 32,
    creatorName: "Community Reserve Creator",
    creatorRole: "Reserve Creator",
  },
  {
    id: "2",
    slug: "colonia-school-reserve",
    name: "Colonia School Reserve",
    summary: "A school campus native garden created by 6th graders that teaches biodiversity while restoring habitat for local pollinators.",
    fullStory: "Sixth graders at Colonia Middle School designed and planted their own MiniNature Reserve as part of a semester-long ecology curriculum. The 200 sq ft campus garden now serves as a living outdoor classroom, attracting butterflies, native bees, and the occasional hummingbird.",
    locationName: "Colonia Middle School",
    address: "1500 Camino Del Sol",
    city: "Oxnard",
    region: "Ventura County",
    lat: 34.2091,
    lng: -119.1614,
    installDate: "2023-09-22",
    reserveType: "school",
    adoptionStatus: "adopted",
    sizeSqft: 200,
    nativePlantCount: 8,
    maintenanceStatus: "thriving",
    featured: true,
    heroPhoto: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    photos: [
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    ],
    species: ["Milkweed", "Purple Needlegrass", "Deerweed", "Sticky Monkeyflower"],
    volunteersCount: 18,
    schoolId: "colonia-middle",
    creatorName: "Colonia 6th Grade Class",
    creatorRole: "School Reserve Team",
  },
  {
    id: "3",
    slug: "rose-avenue-reserve",
    name: "Rose Avenue Parkway Reserve",
    summary: "A grassroots guerrilla reserve started by a neighbor who refused to let the parkway stay bare, now the most visited spot on the block.",
    locationName: "Rose Avenue",
    address: "1200 Rose Avenue",
    city: "Oxnard",
    region: "Ventura County",
    lat: 34.195,
    lng: -119.185,
    installDate: "2022-11-05",
    reserveType: "guerrilla",
    adoptionStatus: "available",
    sizeSqft: 150,
    nativePlantCount: 10,
    maintenanceStatus: "thriving",
    featured: true,
    heroPhoto: "https://images.unsplash.com/photo-1490750967868-88df5691cc11?w=800",
    photos: [
      "https://images.unsplash.com/photo-1490750967868-88df5691cc11?w=800",
    ],
    species: ["California Poppy", "Coastal Sage", "Buckwheat", "Woolly Bluecurls"],
    volunteersCount: 6,
    creatorName: "Neighborhood Steward",
    creatorRole: "Community Reserve Creator",
  },
  {
    id: "4",
    slug: "heritage-square-reserve",
    name: "Heritage Square Reserve",
    summary: "A partnership reserve honoring Chumash plant traditions, installed alongside an indigenous knowledge workshop series.",
    locationName: "Heritage Square Park",
    address: "715 S A Street",
    city: "Oxnard",
    region: "Ventura County",
    lat: 34.1966,
    lng: -119.1728,
    installDate: "2024-02-10",
    reserveType: "paid_partnership",
    adoptionStatus: "adopted",
    sizeSqft: 600,
    nativePlantCount: 22,
    maintenanceStatus: "thriving",
    featured: false,
    heroPhoto: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800",
    photos: [
      "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800",
    ],
    species: ["White Sage", "Black Sage", "Lemonade Berry", "Toyon", "Elder"],
    volunteersCount: 45,
    creatorName: "MiniNature + City of Oxnard",
    creatorRole: "Partnership Reserve",
  },
  {
    id: "5",
    slug: "hueneme-road-reserve",
    name: "Hueneme Road Reserve",
    summary: "A median strip transformed into a drought-tolerant pollinator corridor stretching half a block.",
    locationName: "Hueneme Road Median",
    address: "4500 Hueneme Road",
    city: "Oxnard",
    region: "Ventura County",
    lat: 34.172,
    lng: -119.202,
    installDate: "2023-06-18",
    reserveType: "kit",
    adoptionStatus: "available",
    sizeSqft: 320,
    nativePlantCount: 11,
    maintenanceStatus: "needs_attention",
    featured: false,
    heroPhoto: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800",
    photos: [],
    species: ["Coastal Buckwheat", "California Fuchsia", "Penstemon"],
    volunteersCount: 12,
    creatorName: "Rosa Gutierrez",
    creatorRole: "Kit Reserve Creator",
  },
];

export const EVENTS: Event[] = [
  {
    id: "1",
    slug: "spring-install-day-april-2025",
    title: "Spring MNR Install Day",
    description: "Join us for a full community installation event at three new parkway sites. No experience needed — we provide all plants, tools, and training.",
    eventType: "install",
    locationName: "W 3rd Street, Oxnard",
    address: "310 W 3rd St, Oxnard, CA 93030",
    lat: 34.198,
    lng: -119.175,
    startAt: "2025-04-19T09:00:00",
    endAt: "2025-04-19T14:00:00",
    capacity: 40,
    rsvpCount: 27,
    rsvpUrl: "https://www.eventbrite.com/o/mininature-reserve-30777988501",
  },
  {
    id: "2",
    slug: "indigenous-plants-workshop-may",
    title: "Indigenous Plants & Chumash Heritage Workshop",
    description: "Learn about the deep cultural significance of California native plants from a Chumash knowledge-keeper. Includes plant identification walk and cooking demonstration.",
    eventType: "indigenous_class",
    locationName: "Heritage Square Community Room",
    address: "715 S A St, Oxnard, CA",
    startAt: "2025-05-10T10:00:00",
    endAt: "2025-05-10T13:00:00",
    capacity: 25,
    rsvpCount: 19,
    rsvpUrl: "https://www.eventbrite.com/o/mininature-reserve-30777988501",
  },
  {
    id: "3",
    slug: "colonia-school-volunteer-day",
    title: "School Reserve Volunteer Day",
    description: "Help maintain and expand the Colonia School Reserve. Work alongside students to plant new species and learn about pollinators.",
    eventType: "volunteer",
    reserveId: "2",
    locationName: "Colonia Middle School",
    address: "1500 Camino Del Sol, Oxnard",
    startAt: "2025-04-26T09:30:00",
    endAt: "2025-04-26T12:30:00",
    capacity: 20,
    rsvpCount: 11,
    rsvpUrl: "https://www.eventbrite.com/o/mininature-reserve-30777988501",
  },
];

export const PARTNERS: Partner[] = [
  { id: "1", name: "City of Oxnard", logoUrl: "/logos/oxnard.svg", partnerType: "city", isFeatured: true },
  { id: "2", name: "1% for the Planet", logoUrl: "/logos/1pct.svg", partnerType: "nonprofit", isFeatured: true },
  { id: "3", name: "Ventura County", logoUrl: "/logos/ventura.svg", partnerType: "city", isFeatured: true },
  { id: "4", name: "ViviServe", logoUrl: "/logos/viviserve.svg", partnerType: "nonprofit", isFeatured: true },
  { id: "5", name: "Colonia Middle School", logoUrl: "/logos/colonia.svg", partnerType: "school", isFeatured: false },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    quote: "MiniNature Reserve has greatly piqued my interest in native plants! I have learned so much and there is a great sense of community at these events.",
    authorName: "Community Event Attendee",
    authorRole: "Volunteer",
  },
  {
    id: "2",
    quote: "Watching our students design and plant their own reserve was one of the most powerful teaching moments I've had in 12 years of teaching.",
    authorName: "Partner Teacher",
    authorRole: "6th Grade Science, Colonia Middle School",
  },
  {
    id: "3",
    quote: "I never thought a 4-foot strip of my parkway could become a habitat. Now I see hummingbirds every morning from my kitchen window.",
    authorName: "Reserve Creator",
    authorRole: "Parkway Reserve Steward",
  },
  {
    id: "4",
    quote: "The way MiniNature connects ecological restoration with cultural heritage and community is unlike anything I've seen in the conservation sector.",
    authorName: "Foundation Program Officer",
    authorRole: "Environmental Funder",
  },
];
